/**
 * CLI password resolution.
 *
 * Priority order for `resolveCliPassword`:
 *   1. `--password-fd N`                           (explicit, scripted/CI use)
 *   2. `JINN_PASSWORD` env var                     (explicit, operator-set)
 *   3. `~/.jinn-client/keystore-password` file     (auto-generated by `jinn run`)
 *   4. Error
 *
 * SECURITY TRADE-OFF (known, accepted for Phase 1b testers):
 *   When `jinn run` auto-generates a password, it writes the plaintext
 *   value to `~/.jinn-client/keystore-password` (mode 0o600) and the encrypted
 *   keystore to `~/.jinn-client/earning/master_keystore.json`. An attacker with
 *   shell access to the host can read both and decrypt the mnemonic — the
 *   encryption provides defense only against casual filesystem snooping,
 *   snapshot/backup inclusion policies, and logs. It is NOT protection against
 *   a local attacker.
 *
 *   The run summary warns operators to treat this wallet as hot and to
 *   keep funds to the gas + rewards minimum. The real fix is OS-native secret
 *   storage (macOS Keychain, libsecret, Windows Credential Manager) or a
 *   hardware-backed signer; tracked as future work.
 */

import { existsSync, readFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

export function parsePasswordFdFromArgv(argv: string[]): number | undefined {
  const idx = argv.indexOf('--password-fd');
  if (idx === -1) return undefined;
  const raw = argv[idx + 1];
  const n = raw !== undefined ? parseInt(raw, 10) : NaN;
  if (!Number.isFinite(n) || n < 0) return undefined;
  return n;
}

export function readPasswordFromFd(fd: number): string {
  const buf = readFileSync(fd, { encoding: 'utf8' });
  return buf.replace(/\r?\n$/, '').trim();
}

function mergeArgv(argv?: string[]): string[] {
  const fromVerb = argv ?? [];
  const fromProcess = typeof process !== 'undefined' ? process.argv.slice(2) : [];
  return [...fromVerb, ...fromProcess];
}

function passwordFilePath(env: NodeJS.ProcessEnv): string {
  const home = env['HOME'] ?? homedir();
  return join(home, '.jinn-client', 'keystore-password');
}

function readPasswordFile(env: NodeJS.ProcessEnv): string | undefined {
  const path = passwordFilePath(env);
  if (!existsSync(path)) return undefined;
  const value = readFileSync(path, 'utf-8').trim();
  return value.length > 0 ? value : undefined;
}

export function resolveCliPassword(
  argv?: string[],
  env: NodeJS.ProcessEnv = process.env,
): { ok: true; password: string } | { ok: false; message: string } {
  // 1. --password-fd wins (explicit scripted task).
  const merged = mergeArgv(argv);
  const fd = parsePasswordFdFromArgv(merged);
  if (fd !== undefined) {
    try {
      const password = readPasswordFromFd(fd);
      if (!password) {
        return { ok: false, message: 'Password from --password-fd is empty.' };
      }
      return { ok: true, password };
    } catch (e) {
      return {
        ok: false,
        message: e instanceof Error ? e.message : String(e),
      };
    }
  }

  // 2. JINN_PASSWORD env (explicit operator-set).
  const envPassword = env['JINN_PASSWORD'];
  if (envPassword) return { ok: true, password: envPassword };

  // 3. Auto-generated password file from `jinn run`.
  const filePassword = readPasswordFile(env);
  if (filePassword) return { ok: true, password: filePassword };

  return {
    ok: false,
    message:
      'No keystore password found. Set JINN_PASSWORD, pass --password-fd N, or run `jinn run` to auto-generate one.',
  };
}

export function resolveNewPassword(
  env: Record<string, string | undefined>,
): { ok: true; password: string } | { ok: false; message: string } {
  const newPass = env['JINN_NEW_PASSWORD'];
  if (newPass && newPass.length >= 8) return { ok: true, password: newPass };
  if (newPass && newPass.length < 8)
    return { ok: false, message: 'New password must be at least 8 characters.' };
  return {
    ok: false,
    message: 'Set JINN_NEW_PASSWORD environment variable with your new password (min 8 characters).',
  };
}
