import { spawn, execSync } from 'child_process';
import { writeFileSync, readFileSync, unlinkSync, mkdirSync, existsSync, statSync, symlinkSync, lstatSync, rmSync, copyFileSync } from 'fs';
import { join, dirname, resolve, isAbsolute, delimiter } from 'path';
import { tmpdir, homedir } from 'os';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { agentLogger } from '../logging/index.js';
import { config, secrets } from '../config/index.js';
import { getRepoRoot } from '../shared/repo_utils.js';
import { computeToolPolicy, UNIVERSAL_TOOLS, hasBrowserAutomation, BROWSER_AUTOMATION_TOOLS, hasRailwayDeployment, RAILWAY_TOOLS, hasFirefliesMeetings, FIREFLIES_TOOLS, getEnabledExtensions, EXTENSION_META_TOOLS, getExtensionExcludedTools, type ToolPolicyResult } from './toolPolicy.js';
// Signing proxy is now managed at the worker level (mech_worker.ts)
// Agent subprocess inherits AGENT_SIGNING_PROXY_URL/TOKEN from process.env

dotenv.config({ path: join(process.cwd(), '.env') });

/**
 * Environment variable allowlist for the agent subprocess.
 * Only variables matching these patterns are passed to the agent.
 * Everything else (API keys, service credentials, operator secrets) is blocked.
 *
 * Categories:
 * 1. Operator secrets (PRIVATE_KEY, OPERATE_*) — NEVER passed
 * 2. Operator credentials (GITHUB_TOKEN) — passed directly via allowlist
 * 3. Venture credentials (TELEGRAM_BOT_TOKEN, OPENAI_API_KEY, etc.) — via credential bridge
 * 4. Platform infra (SUPABASE_SERVICE_ROLE_KEY, etc.) — via credential bridge
 * 5. Agent-safe config (below) — passed through
 */
const AGENT_ENV_ALLOWLIST: Array<string | RegExp> = [
  // System
  'PATH', 'HOME', 'USER', 'SHELL', 'LANG', 'TERM', 'TMPDIR',
  'NODE_ENV', 'NODE_PATH', 'NODE_OPTIONS', 'NODE_EXTRA_CA_CERTS',
  'npm_config_cache', 'npm_config_prefix',
  'TZ', /^LC_/,

  // Runtime context generated by worker (trusted internal values)
  /^JINN_CTX_[A-Z0-9_]+$/,
  // Job payload config (untrusted dispatch metadata, validated elsewhere)
  /^JINN_JOB_[A-Z0-9_]+$/,

  // x402 gateway (credential bridge + payment)
  'X402_GATEWAY_URL', 'X402_NETWORK', 'GATEWAY_PAYMENT_ADDRESS',

  // Service endpoints (non-secret URLs/ports)
  'RPC_URL', 'MECHX_CHAIN_RPC', 'MECH_RPC_HTTP_URL', 'BASE_RPC_URL',
  'PONDER_GRAPHQL_URL', 'PONDER_PORT',
  'CONTROL_API_URL', 'CONTROL_API_PORT',
  'IPFS_GATEWAY_URL', 'IPFS_FETCH_TIMEOUT_MS',

  // Gemini CLI config (includes GEMINI_API_KEY — CLI needs it as OAuth fallback)
  /^GEMINI_/,

  // Git identity and code metadata (non-secret)
  /^GIT_AUTHOR_/, /^GIT_COMMITTER_/, /^CODE_METADATA_/,
  'GITHUB_API_URL', 'GITHUB_REPOSITORY',

  // Operator-level credentials (not venture/bridge-scoped)
  'GITHUB_TOKEN',

  // Tool config flags
  'CIVITAI_AIR_WAIT',

  // Mech config (non-secret)
  'MECH_MARKETPLACE_ADDRESS_BASE', 'MECH_MODEL', 'CHAIN_ID',

  // Agent runtime config
  'AGENT_MAX_STDOUT_SIZE', 'AGENT_REPETITION_THRESHOLD',
  'AGENT_SIGNING_PROXY_URL', 'AGENT_SIGNING_PROXY_TOKEN',
  /^STAKING_/,
  'WORKSTREAM_FILTER',

  // Blueprint builder config (non-secret flags)
  /^BLUEPRINT_/,

  // Dev / testing
  'USE_TSX_MCP', 'DEBUG', 'VITEST', 'RUNTIME_ENVIRONMENT',
  'DRY_RUN', 'MCP_LOG_LEVEL', 'DISABLE_STS_CHECKS',

  // OpenTelemetry
  /^OTEL_/,
];

/**
 * Build an environment object containing only allowlisted variables.
 * This prevents secrets (API keys, service credentials, operator keys)
 * from leaking into the agent subprocess.
 */
function buildAllowlistedEnv(): NodeJS.ProcessEnv {
  const result: NodeJS.ProcessEnv = {};
  for (const [key, value] of Object.entries(process.env)) {
    if (value === undefined) continue;
    for (const pattern of AGENT_ENV_ALLOWLIST) {
      if (typeof pattern === 'string') {
        if (key === pattern) { result[key] = value; break; }
      } else {
        if (pattern.test(key)) { result[key] = value; break; }
      }
    }
  }
  return result;
}

const FORBIDDEN_AGENT_ENV_KEYS = [
  'WORKER_PRIVATE_KEY',
  'SERVICE_PRIVATE_KEY',
  'JINN_SERVICE_PRIVATE_KEY',
  'PRIVATE_KEY',
  'SUPABASE_SERVICE_ROLE_KEY',
  'TELEGRAM_BOT_TOKEN',
  'OPENAI_API_KEY',
  'CIVITAI_API_TOKEN',
  'CIVITAI_API_KEY',
  'FIREFLIES_API_KEY',
  'RAILWAY_API_TOKEN',
  'UMAMI_PASSWORD',
  'NANGO_SECRET_KEY',
];

// Bridge-managed secrets must never be injected via MCP settings placeholders.
// They must be fetched at runtime by credential bridge launchers/wrappers.
const BRIDGE_MANAGED_SECRET_PLACEHOLDERS = new Set([
  'TELEGRAM_BOT_TOKEN',
  'OPENAI_API_KEY',
  'CIVITAI_API_TOKEN',
  'CIVITAI_API_KEY',
  'FIREFLIES_API_KEY',
  'RAILWAY_API_TOKEN',
  'SUPABASE_SERVICE_ROLE_KEY',
  'UMAMI_USERNAME',
  'UMAMI_PASSWORD',
  'NANGO_SECRET_KEY',
]);

function assertNoBridgeManagedSecretPlaceholder(value: string, serverName: string, field: string): void {
  const placeholderRegex = /\$\{([A-Z_][A-Z0-9_]*)\}/g;
  const blocked = new Set<string>();
  for (const match of value.matchAll(placeholderRegex)) {
    const envVar = match[1];
    if (BRIDGE_MANAGED_SECRET_PLACEHOLDERS.has(envVar)) {
      blocked.add(envVar);
    }
  }
  if (blocked.size > 0) {
    throw new Error(
      `Forbidden bridge-managed secret placeholder(s) in MCP server "${serverName}" ${field}: ${[...blocked].join(', ')}. ` +
      'Use credential bridge-backed MCP launchers instead of template env substitution.'
    );
  }
}

function isRelativeFileSpecifier(value: string): boolean {
  return value.startsWith('./') || value.startsWith('../');
}

function resolveMcpServerCommandAndArgs(settings: GeminiSettings, agentRoot: string): void {
  if (!settings.mcpServers) return;

  let tsxExecutable: string | undefined;
  try {
    const tsxBinaryName = process.platform === 'win32' ? 'tsx.cmd' : 'tsx';
    const tsxCandidates = [
      resolve(agentRoot, '..', 'node_modules', '.bin', tsxBinaryName),
      resolve(agentRoot, 'node_modules', '.bin', tsxBinaryName),
    ];
    tsxExecutable = tsxCandidates.find(candidate => existsSync(candidate));
  } catch (error) {
    agentLogger.warn({ error: error instanceof Error ? error.message : String(error) }, 'Failed to resolve tsx binary for MCP servers');
  }

  for (const [, serverConfig] of Object.entries(settings.mcpServers)) {
    if (serverConfig.command === 'tsx' && tsxExecutable) {
      serverConfig.command = tsxExecutable;
    } else if (isRelativeFileSpecifier(serverConfig.command) && !isAbsolute(serverConfig.command)) {
      serverConfig.command = resolve(agentRoot, serverConfig.command);
    }

    if (Array.isArray(serverConfig.args)) {
      serverConfig.args = serverConfig.args.map(arg => {
        if (typeof arg === 'string' && isRelativeFileSpecifier(arg) && !isAbsolute(arg)) {
          return resolve(agentRoot, arg);
        }
        return arg;
      });
    }
  }
}

function assertNoForbiddenAgentEnv(env: NodeJS.ProcessEnv): void {
  const leaked = FORBIDDEN_AGENT_ENV_KEYS.filter((key) => Boolean(env[key]));
  if (leaked.length > 0) {
    throw new Error(`Forbidden sensitive env var(s) detected in agent subprocess env: ${leaked.join(', ')}`);
  }
}

/**
 * Strip ANSI escape codes from a string
 * Used to ensure status detection regex works regardless of terminal coloring
 */
function stripAnsi(str: string): string {
  // eslint-disable-next-line no-control-regex
  return str.replace(/\x1b\[[0-9;]*m/g, '');
}

// Add this interface for better type safety
interface MCPServerConfig {
  command: string;
  args?: string[];
  includeTools?: string[];
  excludeTools?: string[];
  trust?: boolean;
  env?: Record<string, string>;
}

export interface GeminiSettings {
  mcpServers?: {
    [serverName: string]: MCPServerConfig;
  };
  tools?: {
    core?: string[];
    exclude?: string[];
    [key: string]: unknown;
  };
  security?: {
    auth?: {
      selectedType?: string;
      enforcedType?: string;
      [key: string]: unknown;
    };
    [key: string]: unknown;
  };
}

interface ToolCall {
  tool: string;
  args?: any;
  duration_ms?: number;
  success: boolean;
  error?: string;
  result?: any;
}

interface JobTelemetry {
  requestText?: any[];
  responseText?: any[];
  inputTokens?: number;
  outputTokens?: number;
  totalTokens: number;
  toolCalls: ToolCall[];
  duration: number;
  errorMessage?: string;
  errorType?: string;
  raw?: any;
}

interface AgentResult {
  output: string;
  structuredSummary?: string;
  jobInstanceStatusUpdate?: string;
  telemetry: JobTelemetry;
}

type JobContext = {
  jobId: string;
  jobDefinitionId: string | null;
  jobName: string;
  workstreamId?: string;
  phase?: string;
  projectRunId: string | null;
  sourceEventId: string | null;
  projectDefinitionId: string | null;
};

/**
 * Substitutes ${ENV_VAR} placeholders in MCP server env blocks with actual values from process.env.
 * Gemini CLI does not automatically pass environment variables to MCP subprocesses,
 * so we need to resolve them at settings generation time.
 */
export function substituteEnvVariables(settings: GeminiSettings): GeminiSettings {
  if (!settings.mcpServers) return settings;

  for (const [serverName, serverConfig] of Object.entries(settings.mcpServers)) {
    if (serverConfig.env) {
      const substitutedEnv: Record<string, string> = {};
      for (const [key, value] of Object.entries(serverConfig.env)) {
        assertNoBridgeManagedSecretPlaceholder(value, serverName, `env.${key}`);
        // Match ${VAR_NAME} pattern
        const match = value.match(/^\$\{([A-Z_][A-Z0-9_]*)\}$/);
        if (match) {
          const envVar = match[1];
          const envValue = process.env[envVar];
          if (!envValue) {
            throw new Error(`Required environment variable ${envVar} not set (needed by MCP server "${serverName}")`);
          }
          substitutedEnv[key] = envValue;
          agentLogger.debug({ serverName, key, envVar }, 'Substituted env variable in MCP config');
        } else {
          // Not a placeholder, use as-is
          substitutedEnv[key] = value;
        }
      }
      serverConfig.env = substitutedEnv;
    }

    // Also substitute ${VAR_NAME} placeholders in args arrays
    if (serverConfig.args) {
      serverConfig.args = serverConfig.args.map(arg => {
        assertNoBridgeManagedSecretPlaceholder(arg, serverName, 'args');
        return arg.replace(/\$\{([A-Z_][A-Z0-9_]*)\}/g, (_, envVar) => {
          const envValue = process.env[envVar];
          if (!envValue) {
            throw new Error(`Required env var ${envVar} not set (needed by MCP server "${serverName}")`);
          }
          return envValue;
        });
      });
    }
  }

  return settings;
}

export class Agent {
  private model: string;
  private enabledTools: string[];
  private settingsPath: string;
  private agentRoot: string;
  private codeWorkspace: string;
  private geminiHome: string;
  private lastTelemetryFile: string | null = null;
  private jobContext?: JobContext;
  private cachedToolPolicy: ToolPolicyResult | null = null;
  private isCodingJob: boolean;
  private onStatusUpdate?: (status: string) => void;
  private lastStatusUpdate: string | null = null;
  private statusBlockBuffer: string | null = null;
  private inStatusBlock: boolean = false;
  private chromeProcess: import('child_process').ChildProcess | null = null;
  private chromeDebugPort: number = 0;
  private chromeUserDataDir: string | null = null;

  // Stdout protection limits (from config)
  private readonly MAX_STDOUT_SIZE = config.agent.maxStdoutSize; // 5MB default
  private readonly MAX_CHUNK_SIZE = config.agent.maxChunkSize; // 100KB default
  private readonly REPETITION_WINDOW = config.agent.repetitionWindow; // Track last 20 lines
  private readonly REPETITION_THRESHOLD = config.agent.repetitionThreshold; // Same line 10+ times = loop
  private readonly MAX_IDENTICAL_CHUNKS = config.agent.maxIdenticalChunks; // Same chunk repeated
  private readonly MAX_PROMPT_ARG_BYTES = config.agent.maxPromptArgBytes; // Avoid E2BIG on spawn

  // Universal tools are now defined in toolPolicy.ts
  private readonly universalTools = UNIVERSAL_TOOLS;

  constructor(
    model: string,
    enabledTools: string[],
    jobContext?: JobContext,
    codeWorkspace?: string | null,
    options?: { isCodingJob?: boolean; onStatusUpdate?: (status: string) => void }
  ) {
    this.model = model;
    this.enabledTools = enabledTools || [];
    this.jobContext = jobContext;
    this.onStatusUpdate = options?.onStatusUpdate;

    // Determine if this is a coding job
    // Primary source: explicit option, fallback to inferring from codeWorkspace
    if (options?.isCodingJob !== undefined) {
      this.isCodingJob = options.isCodingJob;
    } else {
      // Infer from codeWorkspace: null means explicitly non-coding, empty string means no workspace
      this.isCodingJob = codeWorkspace !== null && codeWorkspace !== '';
    }

    // agentRoot must point to the actual gemini-agent directory containing config files
    // Resolve relative to this file's location for reliable path resolution
    // This ensures agentRoot is correct regardless of CODE_METADATA_REPO_ROOT or process.cwd()
    const currentFile = fileURLToPath(import.meta.url);
    const agentDir = dirname(currentFile);
    this.agentRoot = agentDir; // This file is already in gemini-agent directory
    this.settingsPath = join(this.agentRoot, '.gemini', 'settings.json');

    // Verify agentRoot exists and contains expected files
    if (!existsSync(this.agentRoot)) {
      throw new Error(`Agent root directory does not exist: ${this.agentRoot}`);
    }
    const templatePath = join(this.agentRoot, 'settings.template.dev.json');
    const fallbackTemplatePath = join(this.agentRoot, 'settings.template.json');
    if (!existsSync(templatePath) && !existsSync(fallbackTemplatePath)) {
      agentLogger.warn({
        agentRoot: this.agentRoot,
        templatePath,
        fallbackTemplatePath,
        currentFile,
        agentDir
      }, 'Settings template files not found in agentRoot - path resolution may be incorrect');
    }

    // Allow explicit codeWorkspace override (e.g., null for recognition agents)
    // Use shared getRepoRoot logic for codeWorkspace
    // This supports JINN_WORKSPACE_DIR (for ventures) and CODE_METADATA_REPO_ROOT (legacy)
    // Note: We don't have codeMetadata here, so it will fallback to env vars or cwd
    if (codeWorkspace === null) {
      // Explicitly set to null - don't include any workspace (for recognition agents)
      this.codeWorkspace = '';
      agentLogger.debug('codeWorkspace explicitly set to empty (no repo includes)');
    } else if (codeWorkspace) {
      // Explicit codeWorkspace provided
      this.codeWorkspace = codeWorkspace;
      agentLogger.debug({ codeWorkspace }, 'Using explicit codeWorkspace');
    } else {
      // Default behavior: use getRepoRoot()
      const repoRoot = getRepoRoot();
      if (existsSync(repoRoot)) {
        this.codeWorkspace = repoRoot;
      } else {
        agentLogger.warn({ path: repoRoot, fallback: this.agentRoot }, 'Repo root does not exist, falling back to agent root');
        this.codeWorkspace = this.agentRoot;
      }
    }

    // Set Gemini CLI home to /tmp for writable storage (avoids macOS extended attributes)
    // Note: Gemini CLI respects GEMINI_CLI_HOME (not GEMINI_HOME) for extension discovery
    this.geminiHome = join('/tmp', '.gemini-worker');

    // Log protection limits
    agentLogger.info({
      maxStdoutSizeMB: (this.MAX_STDOUT_SIZE / 1024 / 1024).toFixed(1),
      repetitionThreshold: this.REPETITION_THRESHOLD
    }, 'Loop protection enabled');
  }

  /**
   * Check if a Gemini CLI extension is already installed
   */
  private isExtensionInstalled(extensionName: string): boolean {
    // Check workspace scope
    if (this.codeWorkspace) {
      const workspacePath = join(this.codeWorkspace, '.gemini', 'extensions', extensionName);
      if (existsSync(workspacePath)) return true;
    }

    // Check geminiHome scope (runtime location — exported as GEMINI_CLI_HOME)
    const homePath = join(this.geminiHome, 'extensions', extensionName);
    if (existsSync(homePath)) return true;

    // Check ~/.gemini/ scope (legacy — CLI uses GEMINI_CLI_HOME when set)
    const defaultHomePath = join(homedir(), '.gemini', 'extensions', extensionName);
    if (existsSync(defaultHomePath)) return true;

    return false;
  }

  /**
   * Install a Gemini CLI extension (skips if already installed)
   * Supports both remote URLs and local extensions via 'local:' prefix
   */
  private async installExtension(
    extensionUrl: string,
    extensionName: string
  ): Promise<void> {
    // Skip if already installed
    if (this.isExtensionInstalled(extensionName)) {
      agentLogger.debug({ extensionName }, 'Extension already installed, skipping');
      return;
    }

    try {
      // Ensure GEMINI_HOME/extensions exists before installation
      const extensionsDir = join(this.geminiHome, 'extensions');
      mkdirSync(extensionsDir, { recursive: true });

      // Handle local extensions — install directly to GEMINI_HOME (always writable)
      // Avoids ~/.gemini/ conflicts when host directory is mounted in Docker
      if (extensionUrl.startsWith('local:')) {
        const localDir = extensionUrl.replace('local:', '');
        const sourcePath = resolve(this.agentRoot, '..', localDir);

        if (!existsSync(sourcePath)) {
          throw new Error(`Local extension not found: ${sourcePath}`);
        }

        const targetPath = join(this.geminiHome, 'extensions', extensionName);

        // Check if already correctly installed (including stale symlinks)
        try {
          const stats = lstatSync(targetPath);
          if (stats.isSymbolicLink() && existsSync(targetPath)) {
            agentLogger.debug({ extensionName }, 'Local extension already installed in GEMINI_HOME');
            return;
          }
          // Stale or broken — remove
          unlinkSync(targetPath);
        } catch (e: any) {
          if (e.code !== 'ENOENT') throw e;
        }

        mkdirSync(dirname(targetPath), { recursive: true });
        symlinkSync(sourcePath, targetPath);
        agentLogger.info({ sourcePath, targetPath, extensionName }, `Linked local extension ${extensionName} to GEMINI_HOME`);

        // Clean up any broken symlink in ~/.gemini/extensions/ (best effort)
        try {
          const legacyPath = join(homedir(), '.gemini', 'extensions', extensionName);
          const legacyStats = lstatSync(legacyPath);
          if (legacyStats.isSymbolicLink() && !existsSync(legacyPath)) {
            unlinkSync(legacyPath);
            agentLogger.debug({ legacyPath }, 'Cleaned up broken legacy extension symlink');
          }
        } catch { }

        return;
      }

      // Install from remote URL to GEMINI_HOME (persists across jobs)
      // input: 'y\n' auto-confirms the interactive safety prompt
      execSync(
        `npx @google/gemini-cli extension install ${extensionUrl}`,
        {
          cwd: this.codeWorkspace || this.agentRoot,
          stdio: 'pipe',
          input: 'y\n',
          env: { ...process.env, GEMINI_CLI_HOME: this.geminiHome },
        }
      );
      agentLogger.info({ extensionUrl, extensionName }, `Installed ${extensionName} extension`);
    } catch (error) {
      agentLogger.error({ error, extensionUrl, extensionName }, `Failed to install ${extensionName} extension`);
      throw error;
    }
  }

  /**
   * Install all enabled extensions and validate required environment variables
   */
  private async installEnabledExtensions(): Promise<void> {
    const enabledExtensions = getEnabledExtensions(this.enabledTools);

    for (const metaTool of enabledExtensions) {
      const config = EXTENSION_META_TOOLS[metaTool];

      // Skip if no valid config (handles empty EXTENSION_META_TOOLS object)
      if (!config || typeof config !== 'object') continue;

      const typedConfig = config as { requiredEnv: readonly string[]; installUrl: string; extensionName: string };

      // Validate required env vars
      for (const envVar of typedConfig.requiredEnv) {
        if (!process.env[envVar]) {
          throw new Error(`${envVar} required when ${metaTool} is enabled`);
        }
      }

      await this.installExtension(typedConfig.installUrl, typedConfig.extensionName);

      // Ensure extension is in GEMINI_HOME for runtime discovery
      // (CLI may have installed to ~/.gemini/ instead)
      this.ensureExtensionInGeminiHome(typedConfig.extensionName);
    }

    // Patch browser extension config to ensure isolated mode
    this.patchBrowserExtensionConfig();
  }

  /**
   * Patch chrome-devtools extension config to use --isolated=true
   * This ensures each worker gets a temporary user-data-dir, preventing lock conflicts
   * when multiple workers run browser automation concurrently.
   *
   * Checks multiple locations since Gemini CLI may install to ~/.gemini regardless of GEMINI_HOME
   */
  private patchBrowserExtensionConfig(): void {
    // Check multiple possible locations where the extension could be installed
    const possiblePaths = [
      join(this.geminiHome, 'extensions', 'chrome-devtools-mcp', 'gemini-extension.json'),
      join(homedir(), '.gemini', 'extensions', 'chrome-devtools-mcp', 'gemini-extension.json'),
    ];

    // Add workspace scope if available
    if (this.codeWorkspace) {
      possiblePaths.unshift(
        join(this.codeWorkspace, '.gemini', 'extensions', 'chrome-devtools-mcp', 'gemini-extension.json')
      );
    }

    for (const configPath of possiblePaths) {
      if (!existsSync(configPath)) continue;

      try {
        const extensionConfig = JSON.parse(readFileSync(configPath, 'utf-8'));

        if (this.chromeDebugPort > 0) {
          // Connect to pre-launched Chrome via browserUrl
          extensionConfig.mcpServers['chrome-devtools'].args = [
            '-y', 'chrome-devtools-mcp@latest',
            `--browserUrl=http://127.0.0.1:${this.chromeDebugPort}`
          ];
        } else {
          // Fallback: launch own Chrome (only works without sandbox)
          extensionConfig.mcpServers['chrome-devtools'].args = [
            '-y', 'chrome-devtools-mcp@latest', '--headless=true', '--isolated=true'
          ];
        }

        writeFileSync(configPath, JSON.stringify(extensionConfig, null, 2));
        agentLogger.info({ configPath, port: this.chromeDebugPort }, 'Patched chrome-devtools extension config');
      } catch (error) {
        agentLogger.warn({ error: error instanceof Error ? error.message : String(error), configPath }, 'Failed to patch browser extension config');
      }
    }
  }

  /**
   * Ensure extension is available in GEMINI_HOME for CLI runtime discovery.
   * Gemini CLI install may place extensions in ~/.gemini/ regardless of GEMINI_HOME,
   * so we copy them to the runtime GEMINI_HOME if needed.
   */
  private ensureExtensionInGeminiHome(extensionName: string): void {
    const targetPath = join(this.geminiHome, 'extensions', extensionName);

    // Already exists in target location
    if (existsSync(targetPath)) return;

    // Check if it exists in ~/.gemini/
    const homeGeminiPath = join(homedir(), '.gemini', 'extensions', extensionName);
    if (!existsSync(homeGeminiPath)) {
      agentLogger.warn({ extensionName, homeGeminiPath }, 'Extension not found in ~/.gemini/ either');
      return;
    }

    // Copy extension to GEMINI_HOME
    try {
      mkdirSync(dirname(targetPath), { recursive: true });
      // Use cp -r for recursive copy
      execSync(`cp -r "${homeGeminiPath}" "${targetPath}"`, { stdio: 'pipe' });
      agentLogger.info({ extensionName, from: homeGeminiPath, to: targetPath }, 'Copied extension to GEMINI_HOME');
    } catch (error) {
      agentLogger.error({ error, extensionName }, 'Failed to copy extension to GEMINI_HOME');
    }
  }

  /**
   * Launch Chrome with remote debugging before entering the sandbox.
   * Returns the debugging port Chrome is listening on.
   */
  private async launchChrome(): Promise<number> {
    const port = 9222 + Math.floor(Math.random() * 1000);
    const userDataDir = join(tmpdir(), `chrome-worker-${process.pid}-${Date.now()}`);
    mkdirSync(userDataDir, { recursive: true });
    this.chromeUserDataDir = userDataDir;

    const candidates = [
      '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      '/usr/bin/google-chrome',
      '/usr/bin/chromium-browser'
    ];
    let execPath = '';
    for (const p of candidates) {
      if (existsSync(p)) { execPath = p; break; }
    }
    if (!execPath) {
      agentLogger.warn('Chrome not found on system — browser_automation tools will be unavailable');
      return 0;
    }

    const chromeArgs = [
      '--headless',
      '--no-first-run',
      '--no-default-browser-check',
      '--disable-background-networking',
      '--disable-file-url-allow-file-access',
      `--remote-debugging-port=${port}`,
      `--user-data-dir=${userDataDir}`,
    ];
    // In containers (GEMINI_SANDBOX=false), Chrome needs extra flags:
    // --no-sandbox: required for running as non-root in containers
    // --disable-dev-shm-usage: Railway doesn't expose shm_size config;
    //   without this Chrome crashes when /dev/shm is the default 64MB.
    //   Docker Compose handles this via shm_size: 2gb, but Railway has no equivalent.
    if (config.agent.sandbox === 'false') {
      chromeArgs.push('--no-sandbox');
      chromeArgs.push('--disable-dev-shm-usage');
    }
    chromeArgs.push('about:blank');

    this.chromeProcess = spawn(execPath, chromeArgs, { stdio: 'pipe' });

    // Wait for Chrome to be ready (DevTools listening message on stderr)
    await new Promise<void>((resolve, reject) => {
      const timeout = setTimeout(() => reject(new Error('Chrome launch timeout')), 15000);
      this.chromeProcess!.stderr!.on('data', (data: Buffer) => {
        if (data.toString().includes('DevTools listening on')) {
          clearTimeout(timeout);
          resolve();
        }
      });
      this.chromeProcess!.on('error', (err) => { clearTimeout(timeout); reject(err); });
      this.chromeProcess!.on('exit', (code) => { clearTimeout(timeout); reject(new Error(`Chrome exited with ${code}`)); });
    });

    this.chromeDebugPort = port;
    agentLogger.info({ port, userDataDir }, 'Pre-launched Chrome for browser automation');
    return port;
  }

  /**
   * Kill the pre-launched Chrome process and clean up.
   */
  private killChrome(): void {
    if (this.chromeProcess) {
      this.chromeProcess.kill('SIGTERM');
      this.chromeProcess = null;
      agentLogger.info('Killed pre-launched Chrome process');
    }
    if (this.chromeUserDataDir) {
      try {
        rmSync(this.chromeUserDataDir, { recursive: true, force: true });
        agentLogger.debug({ dir: this.chromeUserDataDir }, 'Cleaned up Chrome temp directory');
      } catch {
        // Best-effort cleanup — don't fail the job if this errors
      }
      this.chromeUserDataDir = null;
    }
  }

  public async run(prompt: string): Promise<AgentResult> {
    const startTime = Date.now();
    try {
      // Set job context for tools to access
      if (this.jobContext) {
        // No in-process setter; canonical path is env-only
      }

      // Pre-launch Chrome if browser_automation is enabled (before sandbox kicks in)
      if (hasBrowserAutomation(this.enabledTools)) {
        await this.launchChrome();
      }

      // Install enabled extensions before generating settings
      // Extensions are installed to GEMINI_HOME and persist across jobs
      await this.installEnabledExtensions();

      this.generateJobSpecificSettings();
      // Small delay to allow OpenTelemetry resource attributes to settle
      await new Promise(resolve => setTimeout(resolve, 100));
      const result = await this.runGeminiWithTelemetry(prompt);
      const telemetry = await this.parseTelemetryFromFile(result.telemetryFile, result.output, startTime);

      // Attach last API request for diagnostics
      try {
        const lastReq = telemetry.requestText && telemetry.requestText.length > 0
          ? telemetry.requestText[telemetry.requestText.length - 1]
          : undefined;
        telemetry.raw = telemetry.raw || {};
        if (lastReq) telemetry.raw.lastApiRequest = lastReq;
      } catch { } // Ignore errors here

      // Capture stderr warnings without failing the job
      if (result.stderr && result.stderr.trim()) {
        // Filter out benign stderr lines (startup profiling, info messages)
        const relevantStderr = result.stderr
          .split('\n')
          .filter(line => {
            const trimmed = line.trim();
            if (!trimmed) return false;
            // Filter startup profiler logs
            if (trimmed.startsWith('[STARTUP]')) return false;
            // Filter info messages that go to stderr
            if (trimmed.includes('YOLO mode is enabled')) return false;
            return true;
          })
          .join('\n');

        if (relevantStderr) {
          agentLogger.warn({
            stderrPreview: relevantStderr.substring(0, 200)
          }, 'Warning-level errors detected in stderr');
          telemetry.raw = telemetry.raw || {};
          telemetry.raw.stderrWarnings = relevantStderr;
        }
      }

      // If Gemini exited with non-zero, throw with enriched telemetry
      if (result.exitCode !== 0) {
        // Capture partial output so callers can persist work-in-progress
        try {
          const partialOutput = this.extractFinalOutput(result.output);
          telemetry.raw = telemetry.raw || {};
          (telemetry.raw as any).partialOutput = partialOutput;
        } catch { } // Ignore errors here
        const err = new Error(`Gemini process exited with code ${result.exitCode}`);
        // Preserve stderr in error message context
        (err as any).stderr = result.stderr;
        throw { error: err, telemetry };
      }

      // Extract final output; if tool responses are JSON blobs from our tools, keep them as-is
      const output = this.extractFinalOutput(result.output);

      // Extract structured summary from output (Phase 4)
      const structuredSummary = extractStructuredSummary(output) ?? undefined;

      // Extract job instance status update (Phase 5)
      // Prefer stored lastStatusUpdate (captured from real-time stream), fall back to extraction from output text
      const jobInstanceStatusUpdate = this.lastStatusUpdate ?? extractJobInstanceStatusUpdate(output) ?? undefined;

      return { output, structuredSummary, jobInstanceStatusUpdate, telemetry };
    } catch (error) {
      // Preserve telemetry if the thrown error already includes it (e.g., from non-zero exit path)
      const nestedError = (error as any)?.error ?? error;
      const primaryMessage =
        (nestedError && (nestedError as any).message) ||
        ((error as any)?.message) ||
        String(nestedError ?? error);

      let telemetry: JobTelemetry;
      if (error && typeof error === 'object' && 'telemetry' in (error as any)) {
        // Keep existing telemetry (which may contain raw.partialOutput, toolCalls, etc.)
        telemetry = (error as any).telemetry as JobTelemetry;
        telemetry.duration = telemetry.duration || (Date.now() - startTime);
        telemetry.errorMessage = telemetry.errorMessage || String(primaryMessage);
        telemetry.errorType = telemetry.errorType || this.categorizeError(nestedError);
      } else {
        telemetry = {
          totalTokens: 0,
          toolCalls: [],
          duration: Date.now() - startTime,
          errorMessage: String(primaryMessage),
          errorType: this.categorizeError(nestedError)
        };
      }
      // Preserve the original shape { error, telemetry } but ensure `error` is the actual Error, not the wrapper
      throw { error: nestedError, telemetry };
    } finally {
      // Always clean up Chrome
      this.killChrome();
      // Clear job context
      if (this.jobContext) {
        // No in-process clear; canonical path is env-only
      }
      this.cleanupJobSpecificSettings();
      // Note: telemetry file cleanup handled in runGeminiWithTelemetry result
    }
  }

  private async runGeminiWithTelemetry(prompt: string): Promise<{ output: string; telemetryFile: string; stderr: string; exitCode: number }> {
    // Signing proxy is managed at the worker level (mech_worker.ts)
    // AGENT_SIGNING_PROXY_URL and AGENT_SIGNING_PROXY_TOKEN flow from process.env
    // through buildAllowlistedEnv() into the agent subprocess environment.

    return new Promise((resolvePromise) => {
      // Initialize CLI args
      // NOTE: Gemini CLI no longer accepts --approval-mode or --allowed-tools flags
      // Tool permissions are now controlled via MCP settings.json (includeTools/excludeTools)
      const args: string[] = [];

      // Use cached tool policy (computed in generateJobSpecificSettings)
      // This ensures tool access is properly restricted via MCP settings
      const toolPolicy = this.cachedToolPolicy || computeToolPolicy(this.enabledTools, { isCodingJob: this.isCodingJob });

      // Make sure Gemini CLI treats the job repo as part of the workspace to allow write_file
      const includeDirectories = new Set<string>();
      if (this.codeWorkspace && this.codeWorkspace.trim() !== '') {
        const resolvedWorkspace = resolve(this.codeWorkspace);
        agentLogger.debug({ workspace: resolvedWorkspace }, 'Adding codeWorkspace to include directories');
        includeDirectories.add(resolvedWorkspace);
      } else if (!this.codeWorkspace || this.codeWorkspace.trim() === '') {
        agentLogger.debug('codeWorkspace is empty - skipping all directory includes (including env vars)');
      }

      // Only add environment variable directories if codeWorkspace is not explicitly empty
      if (this.codeWorkspace && this.codeWorkspace.trim() !== '') {
        if (config.git.repoRoot) {
          const resolvedEnv = resolve(config.git.repoRoot);
          agentLogger.debug({ repoRoot: resolvedEnv }, 'Adding CODE_METADATA_REPO_ROOT to include directories');
          includeDirectories.add(resolvedEnv);
        }
        if (config.agent.additionalIncludeDirs) {
          for (const rawDir of config.agent.additionalIncludeDirs.split(delimiter)) {
            if (rawDir?.trim()) {
              includeDirectories.add(resolve(rawDir.trim()));
            }
          }
        }
      }
      for (const dir of includeDirectories) {
        try {
          if (dir && existsSync(dir)) {
            args.push('--include-directories', dir);
          } else {
            agentLogger.debug({ dir }, 'Skipping non-existent include directory for Gemini CLI');
          }
        } catch (err: any) {
          agentLogger.debug({ dir, error: err?.message }, 'Failed to register include directory for Gemini CLI');
        }
      }

      if (this.model) {
        args.unshift('--model', this.model);
      }

      // Force YOLO mode so write tools are available in non-interactive runs
      args.push('--yolo');

      // Debug passthrough
      if (process.argv.includes('--debug') || process.argv.includes('-d')) {
        args.push('--debug');
      }

      // Telemetry outfile — JINN_TELEMETRY_DIR overrides tmpdir() so Docker can mount
      // a host volume for telemetry without polluting TMPDIR with non-telemetry temp files.
      const telemetryDir = config.agent.telemetryDir || tmpdir();
      const telemetryFile = join(telemetryDir, `telemetry-${Date.now()}-${Math.random().toString(36).substr(2, 9)}.json`);
      this.lastTelemetryFile = telemetryFile;

      // Persist the last prompt locally for debugging/repro
      const promptDir = dirname(this.settingsPath);
      try { mkdirSync(promptDir, { recursive: true }); } catch { } // Ignore errors here
      const lastPromptPath = join(promptDir, 'last-prompt.txt');
      try { writeFileSync(lastPromptPath, prompt, 'utf8'); } catch { } // Ignore errors here

      agentLogger.info({ telemetryFile }, 'Will write telemetry to file');
      agentLogger.info({
        model: this.model,
        jobName: this.jobContext?.jobName || 'job',
        workstreamId: this.jobContext?.workstreamId || process.env.JINN_CTX_WORKSTREAM_ID || undefined,
        phase: this.jobContext?.phase || 'execution'
      }, 'Spawning Gemini CLI');

      const promptBytes = Buffer.byteLength(prompt, 'utf8');
      const useStdinPrompt = promptBytes > this.MAX_PROMPT_ARG_BYTES;

      // Use -p flag for small prompts (NOT positional argument)
      // CLI v0.11.2 ignores positional prompts when cwd is a git repository
      // For large prompts, pipe via stdin to avoid E2BIG on spawn
      if (!useStdinPrompt) {
        args.push('-p', prompt);
      }

      // Build agent environment from allowlist — only non-secret config passes through.
      // API keys, service credentials, and operator secrets are blocked by default.
      // Venture credentials are fetched dynamically via the credential bridge.
      const envWithJob: NodeJS.ProcessEnv = buildAllowlistedEnv();
      assertNoForbiddenAgentEnv(envWithJob);

      // AGENT_SIGNING_PROXY_URL and AGENT_SIGNING_PROXY_TOKEN are inherited
      // from process.env via AGENT_ENV_ALLOWLIST — no explicit injection needed

      // Configure telemetry via environment variables (CLI 0.11+ no longer accepts telemetry flags)
      envWithJob.GEMINI_TELEMETRY_ENABLED = 'true';
      envWithJob.GEMINI_TELEMETRY_TARGET = envWithJob.GEMINI_TELEMETRY_TARGET || 'local';
      envWithJob.GEMINI_TELEMETRY_OUTFILE = telemetryFile;
      envWithJob.GEMINI_TELEMETRY_LOG_PROMPTS = envWithJob.GEMINI_TELEMETRY_LOG_PROMPTS || 'true';
      if (!('GEMINI_TELEMETRY_OTLP_ENDPOINT' in envWithJob)) {
        envWithJob.GEMINI_TELEMETRY_OTLP_ENDPOINT = '';
      }
      if (!('GEMINI_TELEMETRY_USE_COLLECTOR' in envWithJob)) {
        envWithJob.GEMINI_TELEMETRY_USE_COLLECTOR = 'false';
      }
      try {
        if (this.jobContext) {
          envWithJob.JINN_CTX_JOB_ID = this.jobContext.jobId || '';
          envWithJob.JINN_CTX_JOB_DEFINITION_ID = this.jobContext.jobDefinitionId || '';
          envWithJob.JINN_CTX_JOB_NAME = this.jobContext.jobName || '';
          envWithJob.JINN_CTX_WORKSTREAM_ID = this.jobContext.workstreamId || envWithJob.JINN_CTX_WORKSTREAM_ID || '';
          envWithJob.JINN_CTX_PROJECT_RUN_ID = this.jobContext.projectRunId || '';
          envWithJob.JINN_CTX_SOURCE_EVENT_ID = this.jobContext.sourceEventId || '';
          envWithJob.JINN_CTX_PROJECT_DEFINITION_ID = this.jobContext.projectDefinitionId || '';
        }
      } catch { } // Ignore errors here

      if (!envWithJob.GEMINI_CLI_SYSTEM_SETTINGS_PATH) {
        envWithJob.GEMINI_CLI_SYSTEM_SETTINGS_PATH = this.settingsPath;
      }
      if (!envWithJob.GEMINI_CLI_SYSTEM_DEFAULTS_PATH) {
        envWithJob.GEMINI_CLI_SYSTEM_DEFAULTS_PATH = this.settingsPath;
      }
      if (useStdinPrompt) {
        envWithJob.GEMINI_SANDBOX = 'false';
        agentLogger.warn({
          promptBytes,
          maxPromptArgBytes: this.MAX_PROMPT_ARG_BYTES
        }, 'Prompt too large for argv; piping via stdin and disabling sandbox');
      }

      // GEMINI_CLI_HOME controls where Gemini CLI looks for extensions, config, AND auth.
      // CLI 0.28+ reads ALL config from GEMINI_CLI_HOME/.gemini/ (not ~/.gemini/).
      const geminiHome = join('/tmp', '.gemini-worker');
      const userGeminiDir = join(homedir(), '.gemini');
      const cliGeminiDir = join(geminiHome, '.gemini');
      try {
        mkdirSync(geminiHome, { recursive: true });
        mkdirSync(userGeminiDir, { recursive: true });
        mkdirSync(cliGeminiDir, { recursive: true });
        envWithJob.GEMINI_CLI_HOME = geminiHome;

        // Copy OAuth credentials from ~/.gemini/ → GEMINI_CLI_HOME/.gemini/
        // Source files are either volume-mounted (Docker E2E) or written by geminiQuota.ts (production).
        for (const file of ['oauth_creds.json', 'google_accounts.json', 'settings.json']) {
          const src = join(userGeminiDir, file);
          const dst = join(cliGeminiDir, file);
          if (existsSync(src)) {
            copyFileSync(src, dst);
          }
        }
      } catch (err: any) {
        agentLogger.debug({ error: err.message }, 'Failed to set up gemini directories');
      }

      const sandboxMode = useStdinPrompt ? 'false' : config.agent.sandbox;

      const geminiProcess = spawn('npx', ['@google/gemini-cli', ...args], {
        // Use stable cwd for Gemini CLI to prevent initialization hang in test environments.
        // Gemini CLI v0.11.2 hangs when spawned with cwd pointing to ephemeral/temporary directories.
        // Tests create temporary fixtures in /var/folders/.../jinn-gemini-tests/, which causes CLI to hang
        // during initialization (likely filesystem metadata/permission issues with transient paths).
        // Solution: Use stable agentRoot as cwd, but expose workspace via JINN_WORKSPACE_DIR env var
        // so native tools (write_file, etc.) can resolve paths correctly.
        cwd: (() => {
          const workspace = this.codeWorkspace && this.codeWorkspace.trim() !== ''
            ? this.codeWorkspace
            : this.agentRoot;

          // If workspace is a temporary test fixture, use agentRoot (stable directory)
          if (workspace.includes('/jinn-gemini-tests/') || process.env.VITEST === 'true') {
            return this.agentRoot; // Stable directory (gemini-agent/)
          }

          return workspace;
        })(),
        env: {
          ...envWithJob,
          // Set GEMINI_CLI_HOME so CLI discovers extensions in /tmp/.gemini-worker/
          GEMINI_CLI_HOME: geminiHome,
          // Expose workspace directory for native tools even when cwd is stable
          ...(this.codeWorkspace && this.codeWorkspace.trim() !== '' ? { JINN_WORKSPACE_DIR: this.codeWorkspace } : {}),
          // Enable sandbox mode (default: 'sandbox-exec' for macOS Seatbelt isolation)
          // Chrome is pre-launched outside the sandbox, so sandbox can stay enabled
          GEMINI_SANDBOX: sandboxMode,
        }
      });

      let stdout = '';
      let stderr = '';
      let terminated = false;
      let terminationReason = '';

      if (useStdinPrompt) {
        try {
          geminiProcess.stdin.write(prompt);
          geminiProcess.stdin.end();
        } catch (stdinError: any) {
          agentLogger.warn({ error: stdinError?.message }, 'Failed to write prompt to stdin');
        }
      }

      // Tracking variables for protection
      // Consecutive-only line repetition tracking
      let lastTrackedLine: string | null = null;
      let consecutiveRepeatCount = 0;
      const chunkHistory: string[] = [];
      let lineCount = 0;
      let lastLineTime = Date.now();

      // Process timeout: kill after 15 minutes to prevent zombie processes
      const PROCESS_TIMEOUT_MS = 15 * 60 * 1000; // 15 minutes
      const processTimeout = setTimeout(() => {
        if (!terminated) {
          terminated = true;
          terminationReason = `Process timeout after ${PROCESS_TIMEOUT_MS >= 60000 ? PROCESS_TIMEOUT_MS / 60000 + ' minutes' : PROCESS_TIMEOUT_MS / 1000 + ' seconds'}`;
          agentLogger.warn({ timeoutMs: PROCESS_TIMEOUT_MS }, 'Terminating process due to timeout');
          geminiProcess.kill('SIGTERM');
        }
      }, PROCESS_TIMEOUT_MS);

      // Prompt is provided as positional argument, no stdin needed

      geminiProcess.stdout.on('data', (data) => {
        if (terminated) return;

        const chunk = data.toString();

        // Check chunk size
        if (chunk.length > this.MAX_CHUNK_SIZE) {
          agentLogger.warn({ chunkSize: chunk.length, maxChunkSize: this.MAX_CHUNK_SIZE }, 'Terminating process due to large chunk');
          terminated = true;
          terminationReason = `Large chunk detected: ${chunk.length} bytes`;
          geminiProcess.kill('SIGTERM');
          return;
        }

        // Check total stdout size
        if (stdout.length + chunk.length > this.MAX_STDOUT_SIZE) {
          const totalSizeMB = ((stdout.length + chunk.length) / 1024 / 1024).toFixed(2);
          agentLogger.warn({ totalSizeBytes: stdout.length + chunk.length, maxSizeBytes: this.MAX_STDOUT_SIZE, totalSizeMB }, 'Terminating process due to output size limit');
          terminated = true;
          terminationReason = `Output size limit exceeded: ${totalSizeMB}MB`;
          geminiProcess.kill('SIGTERM');
          return;
        }

        // Check for identical chunk repetition
        chunkHistory.push(chunk);
        if (chunkHistory.length > this.MAX_IDENTICAL_CHUNKS) {
          chunkHistory.shift();
        }

        const identicalChunks = chunkHistory.filter(c => c === chunk).length;
        if (identicalChunks >= this.MAX_IDENTICAL_CHUNKS) {
          agentLogger.warn({ identicalChunks, maxIdenticalChunks: this.MAX_IDENTICAL_CHUNKS }, 'Terminating process due to identical chunk repetition');
          terminated = true;
          terminationReason = `Identical chunks repeated ${identicalChunks} times`;
          geminiProcess.kill('SIGTERM');
          return;
        }

        // Process lines for repetition detection and rate limiting
        const lines = chunk.split('\n');
        const currentTime = Date.now();

        for (const line of lines) {
          if (line.trim().length > 0) {
            lineCount++;

            // Removed per-second output rate limiting

            // Line repetition detection (consecutive-only) with benign prefix ignore
            const isBenignPrefix = /^\s*call:/i.test(line);
            if (!isBenignPrefix) {
              if (lastTrackedLine === line) {
                consecutiveRepeatCount += 1;
              } else {
                lastTrackedLine = line;
                consecutiveRepeatCount = 1;
              }
              if (consecutiveRepeatCount >= this.REPETITION_THRESHOLD) {
                agentLogger.warn({
                  consecutiveRepeatCount,
                  repetitionThreshold: this.REPETITION_THRESHOLD,
                  linePreview: line.substring(0, 100)
                }, 'Terminating process due to consecutive repetitive output');
                terminated = true;
                terminationReason = `Consecutive repetitive line detected ${consecutiveRepeatCount} times`;
                geminiProcess.kill('SIGTERM');
                return;
              }
            } else {
              // Reset repetition tracking when encountering benign prefixes
              lastTrackedLine = null;
              consecutiveRepeatCount = 0;
            }

          }

          // Detect status updates in the output stream for real-time and delivery payload inclusion
          // Strip ANSI codes to ensure reliable pattern matching
          const cleanLine = stripAnsi(line);

          // Pattern 1: Fenced status block (```status ... ```)
          // Multi-line status updates are buffered until the closing fence
          const statusBlockStart = /^```status\s*$/i;
          const statusBlockEnd = /^```\s*$/;
          const trimmedCleanLine = cleanLine.trim();

          if (statusBlockStart.test(trimmedCleanLine)) {
            this.inStatusBlock = true;
            this.statusBlockBuffer = '';
          } else if (this.inStatusBlock) {
            if (statusBlockEnd.test(trimmedCleanLine)) {
              // Emit the complete status block
              const status = (this.statusBlockBuffer || '').replace(/\s+/g, ' ').trim();
              if (status.length > 0 && status.length <= 144) {
                this.lastStatusUpdate = status;
                if (this.onStatusUpdate) {
                  this.onStatusUpdate(status);
                }
              }
              this.inStatusBlock = false;
              this.statusBlockBuffer = null;
            } else {
              // Accumulate lines within the status block
              this.statusBlockBuffer = (this.statusBlockBuffer || '') +
                (this.statusBlockBuffer ? ' ' : '') + trimmedCleanLine;
            }
          }

          // Pattern 2: TaskStatus from tool calls ("TaskStatus": "Value" or TaskStatus="Value")
          // Only check when not in a status block
          if (!this.inStatusBlock) {
            const taskStatusMatch = cleanLine.match(/"?TaskStatus"?\s*[:=]\s*"([^"]+)"/);
            if (taskStatusMatch && taskStatusMatch[1]) {
              const status = taskStatusMatch[1];
              this.lastStatusUpdate = status;
              if (this.onStatusUpdate) {
                this.onStatusUpdate(status);
              }
            }
            // Pattern 3: Legacy explicit text markers (Status Update: ...)
            const textStatusMatch = cleanLine.match(/(?:\*\*|#+\s*)?Status Update:?(?:\*\*)?\s*(.+?)$/i);
            if (textStatusMatch && textStatusMatch[1]) {
              const status = textStatusMatch[1].trim();
              if (status.length > 0 && status.length <= 144) {
                this.lastStatusUpdate = status;
                if (this.onStatusUpdate) {
                  this.onStatusUpdate(status);
                }
              }
            }
          }

          // Console logging (existing logic)
          const truncatedLine = line.length > 200 ? line.substring(0, 200) + '...' : line;
          agentLogger.output(truncatedLine);
        }

        // Add chunk to stdout if not terminated
        stdout += chunk;
      });

      // Exception: Uses console.error for subprocess stderr forwarding (per spec: "Subprocess streaming in process managers")
      // This forwards Gemini CLI stderr to console for operational visibility
      geminiProcess.stderr.on('data', (data) => {
        const chunk = data.toString();
        chunk.split('\n').forEach((line: string) => {
          const trimmed = line.trim();
          if (trimmed.length > 0) {
            // Filter out benign stderr patterns from live streaming
            if (trimmed.startsWith('[STARTUP]')) return;
            if (trimmed.includes('YOLO mode is enabled')) return;

            const truncatedLine = line.length > 200 ? line.substring(0, 200) + '...' : line;
            console.error(truncatedLine);
          }
        });
        stderr += chunk;
      });

      geminiProcess.on('close', (code) => {
        clearTimeout(processTimeout);

        // Signing proxy cleanup is now handled at worker level (mech_worker.ts)

        // Inspect stderr for API/tool errors even if process exits 0
        let hasApiError = (stderr && (
          stderr.includes('Error when talking to Gemini API') ||
          stderr.toLowerCase().includes('could not parse tool response')
        )) || false;
        const rawExit = typeof code === 'number' ? code : 0;
        let exitCode = hasApiError ? (rawExit || 1) : rawExit;

        // Downgrade specific tool errors to warnings so the process can continue successfully
        const isToolNotFound = typeof stderr === 'string' && /tool\s+"?.+?"?\s+not\s+found\s+in\s+registry/i.test(stderr);
        if (isToolNotFound) {
          // Treat as warning-only: do not fail the run on missing tool
          hasApiError = false;
          exitCode = 0;
        }

        // Handle termination cases
        if (terminated) {
          agentLogger.warn({ terminationReason }, 'Process terminated by loop detection');
          // Add termination reason to output for debugging
          stdout += `\n\n[PROCESS TERMINATED: ${terminationReason}]`;
          // Force non-zero exit code for terminated processes
          exitCode = exitCode || 1;
        }

        resolvePromise({ output: stdout, telemetryFile, stderr, exitCode });
      });

      geminiProcess.on('error', (err) => {
        clearTimeout(processTimeout);
        // Signing proxy cleanup is handled at worker level (mech_worker.ts)

        // Surface as a synthetic non-zero exit with captured streams
        const exitCode = 1;
        const synthetic = `Gemini spawn error: ${err?.message || String(err)}`;
        resolvePromise({ output: stdout, telemetryFile, stderr: `${stderr}\n${synthetic}`.trim(), exitCode });
      });
    });
  }

  private generateJobSpecificSettings(): void {
    // Always generate settings if we have universal tools, even if no job-specific tools
    if (this.enabledTools.length === 0 && (this.universalTools as readonly string[]).length === 0) return;
    try {
      const useTsxTemplate = config.dev.useTsxMcp;
      if (!useTsxTemplate) {
        const compiledMcpEntry = join(this.agentRoot, 'mcp', 'server.js');
        if (!existsSync(compiledMcpEntry)) {
          throw new Error(
            `Compiled MCP entry missing: ${compiledMcpEntry}\n` +
            'Either run the compiled build with mcp/server.js present, or run in source mode with USE_TSX_MCP=1.',
          );
        }
      }

      const templateFileName = useTsxTemplate
        ? 'settings.template.dev.json'
        : 'settings.template.json';
      const templatePath = join(this.agentRoot, templateFileName);

      // Verify template file exists before reading
      if (!existsSync(templatePath)) {
        const fallbackPath = join(this.agentRoot, templateFileName === 'settings.template.dev.json'
          ? 'settings.template.json'
          : 'settings.template.dev.json');
        const attemptedPaths = [templatePath];
        if (existsSync(fallbackPath)) {
          attemptedPaths.push(`(fallback exists: ${fallbackPath})`);
        }
        throw new Error(
          `Settings template file not found: ${templatePath}\n` +
          `Agent root: ${this.agentRoot}\n` +
          `Attempted paths: ${attemptedPaths.join(', ')}\n` +
          `Current working directory: ${process.cwd()}`
        );
      }

      const templateSettings: GeminiSettings = JSON.parse(readFileSync(templatePath, 'utf8'));

      // Dynamically resolve auth type based on available credentials.
      // GEMINI_API_KEY → "gemini-api-key", otherwise fall back to "oauth-personal".
      // This prevents the template from hardcoding an auth type that conflicts
      // with the user's ~/.gemini/settings.json (which init.sh configures).
      if (!templateSettings.security) templateSettings.security = {};
      if (!templateSettings.security.auth) templateSettings.security.auth = {};
      templateSettings.security.auth.selectedType = secrets.geminiApiKey
        ? 'gemini-api-key'
        : 'oauth-personal';

      if (!templateSettings.mcpServers) {
        throw new Error('No MCP servers configured in settings.template.json');
      }

      // Remove unused servers BEFORE substituting env variables to avoid
      // errors when env vars for unused servers are not set
      // Conditionally include railway server based on railway_deployment meta-tool
      if (templateSettings.mcpServers['railway'] && !hasRailwayDeployment(this.enabledTools)) {
        delete templateSettings.mcpServers['railway'];
        agentLogger.debug('Removed railway server (railway_deployment not enabled)');
      }

      // Conditionally include fireflies server based on fireflies_meetings meta-tool
      if (templateSettings.mcpServers['fireflies'] && !hasFirefliesMeetings(this.enabledTools)) {
        delete templateSettings.mcpServers['fireflies'];
        agentLogger.debug('Removed fireflies server (fireflies_meetings not enabled)');
      }

      // Substitute ${ENV_VAR} placeholders in MCP server env blocks
      // Done AFTER removing unused servers so we don't fail on missing env vars for disabled servers
      substituteEnvVariables(templateSettings);

      // Resolve server command + argument paths for every MCP server entry.
      // This keeps wrapper paths stable regardless of process cwd.
      resolveMcpServerCommandAndArgs(templateSettings, this.agentRoot);

      const serverName = templateSettings.mcpServers.metacog ? 'metacog' : Object.keys(templateSettings.mcpServers)[0];
      if (!serverName) throw new Error('No MCP servers found in template configuration');

      const mcpServer = templateSettings.mcpServers[serverName];
      if (!mcpServer) throw new Error(`MCP server '${serverName}' not found in template configuration`);

      // Compute tool policy using centralized logic
      // This ensures MCP include/exclude and CLI whitelist are consistent
      // Cache it for reuse in runGeminiWithTelemetry to avoid double computation
      this.cachedToolPolicy = computeToolPolicy(this.enabledTools, { isCodingJob: this.isCodingJob });
      const toolPolicy = this.cachedToolPolicy;

      // Filter browser tools from metacog's includeTools - they don't belong there
      // metacog only provides our custom tools (get_details, dispatch_new_job, etc.)
      const browserToolSet = new Set(BROWSER_AUTOMATION_TOOLS as readonly string[]);
      const metacogTools = toolPolicy.mcpIncludeTools.filter(t => !browserToolSet.has(t));
      mcpServer.includeTools = metacogTools;

      // If railway server is present, set its includeTools to railway deployment tools
      if (templateSettings.mcpServers['railway']) {
        const railwayToolSet = new Set(RAILWAY_TOOLS as readonly string[]);
        const railwayTools = toolPolicy.mcpIncludeTools.filter(t => railwayToolSet.has(t));
        templateSettings.mcpServers['railway'].includeTools = railwayTools;
      }

      // If fireflies server is present, set its includeTools to fireflies meeting tools
      if (templateSettings.mcpServers['fireflies']) {
        const firefliesToolSet = new Set(FIREFLIES_TOOLS as readonly string[]);
        const firefliesTools = toolPolicy.mcpIncludeTools.filter(t => firefliesToolSet.has(t));
        templateSettings.mcpServers['fireflies'].includeTools = firefliesTools;
      }

      // CRITICAL: Do NOT set global excludeTools for MCP tools - it overrides per-server includeTools
      // The Gemini CLI respects per-server includeTools without needing global exclusions
      // templateSettings.excludeTools = toolPolicy.mcpExcludeTools;

      // Collect all excluded tools from enabled extensions (e.g., telegram's 'read' tool)
      // These are added to global tools.exclude to prevent prompt injection risks
      // Gemini CLI reads this from settings.tools.exclude (not top-level excludeTools)
      if (!templateSettings.tools) templateSettings.tools = {};
      const extensionExcludedTools = getExtensionExcludedTools(this.enabledTools);
      if (extensionExcludedTools.length > 0) {
        templateSettings.tools.exclude = [
          ...(templateSettings.tools.exclude || []),
          ...extensionExcludedTools
        ];
        agentLogger.debug({ extensionExcludedTools }, 'Added extension excluded tools to settings');
      }

      // Block browser automation tools when browser_automation meta-tool is not enabled
      // This prevents agents from accidentally using browser tools without explicit permission
      if (!hasBrowserAutomation(this.enabledTools)) {
        templateSettings.tools.exclude = [
          ...(templateSettings.tools.exclude || []),
          ...BROWSER_AUTOMATION_TOOLS
        ];
        agentLogger.debug('Blocked browser automation tools (browser_automation not enabled)');
      }

      // Whitelist native tools at the CLI level (write_file, replace, etc.)
      // Gemini CLI reads this from settings.tools.core (not top-level coreTools)
      if (!templateSettings.tools) templateSettings.tools = {};
      templateSettings.tools.core = toolPolicy.cliAllowedTools;

      // Ensure directory exists
      const settingsDir = dirname(this.settingsPath);
      mkdirSync(settingsDir, { recursive: true });

      writeFileSync(this.settingsPath, JSON.stringify(templateSettings, null, 2));
      agentLogger.info({
        serverName,
        mcpIncludeTools: toolPolicy.mcpIncludeTools,
        universalTools: UNIVERSAL_TOOLS,
        jobSpecificTools: this.enabledTools.length > 0 ? this.enabledTools : 'none',
        mcpExcludedTools: toolPolicy.mcpExcludeTools.length > 0 ? toolPolicy.mcpExcludeTools : 'none',
        cliAllowedTools: toolPolicy.cliAllowedTools
      }, 'Generated job-specific settings');
    } catch (error) {
      const errorMsg = error instanceof Error ? error.message : String(error);
      agentLogger.error({ error: errorMsg }, 'Failed to generate job-specific settings');
      throw error;
    }
  }

  private cleanupJobSpecificSettings(): void {
    // Always cleanup if we have universal tools, even if no job-specific tools
    if (this.enabledTools.length === 0 && (this.universalTools as readonly string[]).length === 0) return;
    try {
      unlinkSync(this.settingsPath);
      agentLogger.debug({ settingsPath: this.settingsPath }, 'Cleaned up job-specific settings');
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        const errorMsg = error instanceof Error ? error.message : String(error);
        agentLogger.warn({ error: errorMsg, settingsPath: this.settingsPath }, 'Failed to clean up job-specific settings');
      }
    }
    // Clear cached tool policy
    this.cachedToolPolicy = null;
  }

  private cleanupTelemetryFile(telemetryFile: string): void {
    if (!telemetryFile || telemetryFile.trim() === '') return;
    try {
      unlinkSync(telemetryFile);
      agentLogger.debug({ telemetryFile }, 'Cleaned up telemetry file');
    } catch (error: any) {
      if (error.code !== 'ENOENT') {
        const errorMsg = error instanceof Error ? error.message : String(error);
        agentLogger.warn({ error: errorMsg, telemetryFile }, 'Failed to clean up telemetry file');
      }
    }
  }

  private parseTelemetryFromOutput(output: string, startTime: number): JobTelemetry {
    const telemetry: JobTelemetry = {
      totalTokens: 0,
      toolCalls: [],
      duration: Date.now() - startTime,
      raw: {}
    };

    try {
      const telemetryData = this.parseStructuredTelemetry(output);
      telemetry.totalTokens = telemetryData.totalTokens || 0;
      telemetry.toolCalls = telemetryData.toolCalls || [];
      telemetry.requestText = telemetryData.requestText;
      telemetry.responseText = telemetryData.responseText;

      telemetry.raw = {
        sessionId: telemetryData.sessionId,
        promptId: telemetryData.promptId,
        modelName: telemetryData.modelName,
        originalOutput: output.substring(0, 1000)
      };
    } catch (error: any) {
      agentLogger.error({ error: error instanceof Error ? error.message : String(error) }, 'Error parsing telemetry from output');
      telemetry.errorMessage = `Telemetry parsing failed: ${error.message}`;
      telemetry.raw = { parseError: error.message, output: output.substring(0, 500) };
    }

    return telemetry;
  }

  private async parseTelemetryFromFile(telemetryFile: string | undefined, output: string | undefined, startTime: number): Promise<JobTelemetry> {
    let candidateFile = telemetryFile && telemetryFile.trim() !== ''
      ? telemetryFile
      : (this.lastTelemetryFile && this.lastTelemetryFile.trim() !== '' ? this.lastTelemetryFile : '');

    try {
      if (readFileSync && candidateFile) {
        // Give the CLI a moment to flush the telemetry file if the process just exited.
        const maxAttempts = 40;
        for (let attempt = 0; attempt < maxAttempts; attempt++) {
          if (existsSync(candidateFile)) {
            const size = statSync(candidateFile).size;
            if (size > 0) {
              break;
            }
          }
          await new Promise(resolve => setTimeout(resolve, 250));
        }

        if (!existsSync(candidateFile)) {
          agentLogger.warn({ telemetryFile: candidateFile }, 'Telemetry file still missing after waiting');
        } else if (statSync(candidateFile).size === 0) {
          agentLogger.warn({ telemetryFile: candidateFile }, 'Telemetry file is still empty after waiting');
        } else {
          const telemetryContent = readFileSync(candidateFile, 'utf8');

          // Optional safety: cap processing to avoid runaway memory usage
          const maxProcessChars = 50 * 1024 * 1024; // 50MB
          const contentToParse = telemetryContent.length > maxProcessChars
            ? telemetryContent.substring(0, maxProcessChars)
            : telemetryContent;

          agentLogger.debug({
            telemetryFile: candidateFile,
            contentLength: telemetryContent.length,
            contentPreview: telemetryContent.substring(0, 100)
          }, 'Reading telemetry file');

          const result = this.parseTelemetryFromContent(contentToParse, startTime);
          return result;
        }
      }
    } catch (error: any) {
      agentLogger.warn({
        error: error.message,
        telemetryFile: telemetryFile || this.lastTelemetryFile || 'none'
      }, 'Failed to read telemetry file');
    }

    if (!candidateFile) {
      agentLogger.warn({}, 'Telemetry file path missing; falling back to stdout parsing');
    } else {
      agentLogger.debug({}, 'Falling back to output parsing');
    }
    return this.parseTelemetryFromOutput(output ?? '', startTime);
  }

  // Streaming JSON parser: assembles complete JSON objects from mixed-content file
  private parseTelemetryFromContent(content: string, startTime: number): JobTelemetry {
    const telemetry: JobTelemetry = {
      totalTokens: 0,
      toolCalls: [],
      duration: Date.now() - startTime,
      raw: {}
    };

    try {
      const telemetryEvents: any[] = [];
      let buffer = '';
      let started = false;
      let braceCount = 0;
      let inString = false;
      let escapeNext = false;
      let parseErrors = 0;
      const maxParseErrors = 10;

      for (let i = 0; i < content.length; i++) {
        const ch = content[i];

        if (!started) {
          if (ch === '{') {
            started = true;
            braceCount = 1;
            buffer = '{';
            inString = false;
            escapeNext = false;
          }
          continue;
        }

        buffer += ch;

        if (escapeNext) {
          escapeNext = false;
        } else if (ch === '\\' && inString) {
          escapeNext = true;
        } else if (ch === '"') {
          inString = !inString;
        } else if (!inString) {
          if (ch === '{') braceCount++;
          else if (ch === '}') braceCount--;
        }

        if (started && braceCount === 0) {
          const candidate = buffer.trim();
          try {
            const obj = JSON.parse(candidate);
            telemetryEvents.push(obj);
          } catch (e: any) {
            parseErrors++;
            if (parseErrors <= maxParseErrors) {
              agentLogger.debug({
                error: e.message,
                sample: candidate.substring(0, 120)
              }, 'Failed to parse JSON object in telemetry');
            } else if (parseErrors === maxParseErrors + 1) {
              agentLogger.debug({ parseErrors }, 'Too many parse errors; further errors suppressed');
            }
          }
          started = false;
          buffer = '';
          inString = false;
          escapeNext = false;
        }
      }

      agentLogger.debug({
        eventCount: telemetryEvents.length,
        parseErrors: parseErrors > 0 ? parseErrors : undefined
      }, 'Parsed telemetry events');

      // Process events
      for (const event of telemetryEvents) {
        if (!event || !event.attributes) continue;
        const attrs = event.attributes;
        const eventName = attrs['event.name'];

        if (attrs['session.id'] && !telemetry.raw.sessionId) {
          telemetry.raw.sessionId = attrs['session.id'];
        }

        switch (eventName) {
          case 'gemini_cli.user_prompt':
            if (attrs['prompt']) {
              if (!telemetry.requestText) telemetry.requestText = [];
              telemetry.requestText.push(attrs['prompt']);
            }
            if (attrs['prompt_length']) {
              telemetry.raw.promptLength = attrs['prompt_length'];
            }
            break;

          case 'gemini_cli.api_request':
            if (attrs['request_text']) {
              if (!telemetry.requestText) telemetry.requestText = [];
              telemetry.requestText.push(attrs['request_text']);
            }
            if (attrs['model']) {
              telemetry.raw.model = attrs['model'];
            }
            break;

          case 'gemini_cli.api_response':
            if (attrs['total_token_count'] && typeof attrs['total_token_count'] === 'number') {
              telemetry.totalTokens = Math.max(telemetry.totalTokens, attrs['total_token_count']);
            }
            if (attrs['input_token_count']) {
              // Promote to top-level field and keep in raw for backwards compatibility
              telemetry.inputTokens = (telemetry.inputTokens || 0) + attrs['input_token_count'];
              telemetry.raw.inputTokens = attrs['input_token_count'];
            }
            if (attrs['output_token_count']) {
              // Promote to top-level field and keep in raw for backwards compatibility
              telemetry.outputTokens = (telemetry.outputTokens || 0) + attrs['output_token_count'];
              telemetry.raw.outputTokens = attrs['output_token_count'];
            }
            if (attrs['duration_ms']) {
              telemetry.raw.apiDurationMs = attrs['duration_ms'];
            }
            if (attrs['response_text']) {
              if (!telemetry.responseText) telemetry.responseText = [];
              telemetry.responseText.push(attrs['response_text']);
            }
            break;

          case 'gemini_cli.tool_call':
          case 'gemini_cli.function_call':
            telemetry.toolCalls.push({
              tool: attrs['function_name'] || attrs['tool_name'] || attrs['name'] || 'unknown',
              success: attrs['success'] !== false,
              duration_ms: attrs['duration_ms'] || 0,
              args: attrs['function_args'] || attrs['parameters'] || attrs['args'] || attrs['arguments']
            });
            break;
        }
      }

      // Extract tool results from conversation history and attach to tool calls
      this.attachToolResultsToToolCalls(telemetry);

      telemetry.raw.eventCount = telemetryEvents.length;
      telemetry.raw.events = telemetryEvents.map(e => e.attributes?.['event.name']).filter(Boolean);
      agentLogger.debug({
        totalTokens: telemetry.totalTokens,
        toolCallCount: telemetry.toolCalls.length,
        sessionId: telemetry.raw.sessionId
      }, 'Telemetry parsing completed');
    } catch (error: any) {
      agentLogger.error({ error: error instanceof Error ? error.message : String(error) }, 'Error parsing telemetry content');
      telemetry.errorMessage = `Telemetry file parsing failed: ${error.message}`;
      telemetry.raw = { parseError: error.message, content: content.substring(0, 500) };
    }

    return telemetry;
  }

  private parseStructuredTelemetry(output: string): any {
    const result: any = { toolCalls: [], totalTokens: 0 };
    const lines = output.split('\n');

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      if (line.includes('-> session.id: Str(')) {
        result.sessionId = this.extractValue(line, 'Str');
      } else if (line.includes('-> prompt_id: Str(')) {
        result.promptId = this.extractValue(line, 'Str');
      } else if (line.includes('-> model: Str(')) {
        result.modelName = this.extractValue(line, 'Str');
      } else if (line.includes('-> function_name: Str(')) {
        const functionName = this.extractValue(line, 'Str');
        if (functionName) {
          const duration = this.findDurationNearLine(lines, i);
          result.toolCalls.push({
            tool: functionName,
            duration_ms: duration || 0,
            success: true
          });
        }
      } else if (line.includes('Value: ') && line.includes('Int(')) {
        const tokenValue = this.extractValue(line, 'Int');
        if (tokenValue && parseInt(tokenValue) > result.totalTokens) {
          result.totalTokens = parseInt(tokenValue);
        }
      } else if (line.includes('Tool call:') && line.includes('Duration:')) {
        const toolMatch = line.match(/Tool call: ([^.]+)\. Success: (true|false)\. Duration: (\d+)ms\./);
        if (toolMatch) {
          result.toolCalls.push({
            tool: toolMatch[1],
            success: toolMatch[2] === 'true',
            duration_ms: parseInt(toolMatch[3])
          });
        }
      }
    }

    return result;
  }

  private extractValue(line: string, type: 'Str' | 'Int'): string | null {
    const pattern = type === 'Str' ? /Str\(([^)]+)\)/ : /Int\(([^)]+)\)/;
    const match = line.match(pattern);
    return match ? match[1] : null;
  }

  private findDurationNearLine(lines: string[], startIndex: number): number | null {
    for (let i = startIndex; i < Math.min(startIndex + 5, lines.length); i++) {
      if (lines[i].includes('-> duration_ms: Int(')) {
        const duration = this.extractValue(lines[i], 'Int');
        return duration ? parseInt(duration) : null;
      }
    }
    return null;
  }

  private extractFinalOutput(output: string): string {
    const lines = output.split('\n');
    const finalOutput: string[] = [];

    for (const line of lines) {
      if (line.includes('-> ') || line.includes('Trace ID:') || line.includes('otel-collector')) continue;
      if (line.includes('OpenTelemetry SDK')) continue;
      finalOutput.push(line);
    }

    return finalOutput.join('\n').trim();
  }

  private attachToolResultsToToolCalls(telemetry: JobTelemetry): void {
    if (!telemetry.requestText || telemetry.toolCalls.length === 0) return;

    try {
      // Use the latest/fullest conversation snapshot first; older snapshots are usually cumulative and can
      // otherwise cause response reattachment (same function response mapped to later calls).
      const snapshots = telemetry.requestText
        .filter((t): t is string => typeof t === 'string' && t.trim().length > 0)
        .sort((a, b) => b.length - a.length);

      if (snapshots.length === 0) return;

      const pendingByTool = new Map<string, ToolCall[]>();
      for (const tc of telemetry.toolCalls) {
        if (!tc || typeof tc.tool !== 'string') continue;
        if (tc.result) continue;
        const queue = pendingByTool.get(tc.tool) || [];
        queue.push(tc);
        pendingByTool.set(tc.tool, queue);
      }

      for (const requestText of snapshots) {
        let conversations: any[] = [];
        try {
          const parsed = JSON.parse(requestText);
          if (!Array.isArray(parsed)) continue;
          conversations = parsed;
        } catch {
          continue;
        }

        const responses: Array<{ toolName: string; output: string }> = [];
        for (const message of conversations) {
          if (message?.role !== 'user' || !Array.isArray(message.parts)) continue;
          for (const part of message.parts) {
            const functionResponse = part?.functionResponse;
            if (!functionResponse?.name || !functionResponse?.response?.output) continue;
            responses.push({
              toolName: String(functionResponse.name),
              output: String(functionResponse.response.output),
            });
          }
        }

        if (responses.length === 0) continue;

        for (const response of responses) {
          const queue = pendingByTool.get(response.toolName);
          if (!queue || queue.length === 0) continue;
          const toolCall = queue.shift();
          if (!toolCall) continue;

          try {
            const output = JSON.parse(response.output);
            if (output.data) {
              toolCall.result = output.data;
            } else if (output.error) {
              toolCall.result = { error: output.error };
            } else {
              toolCall.result = output;
            }
          } catch {
            toolCall.result = { rawOutput: response.output };
          }
        }

        // Snapshot successfully processed; avoid remapping from older cumulative snapshots.
        break;
      }
    } catch (error: any) {
      agentLogger.warn({ error: error.message }, 'Failed to attach tool results to telemetry');
    }
  }

  private categorizeError(error: any): string {
    if (!error) return 'UNKNOWN';
    const message = error.message || String(error);

    if (message.includes('exited with code')) return 'PROCESS_ERROR';
    if (message.includes('timeout') || message.includes('Process timeout')) return 'TIMEOUT';
    if (message.includes('PROCESS TERMINATED')) return 'LOOP_PROTECTION';
    if (message.includes('Output size limit') || message.includes('Repetitive line')) return 'LOOP_PROTECTION';
    if (message.includes('High output rate') || message.includes('Large chunk')) return 'LOOP_PROTECTION';
    if (message.includes('ENOTFOUND') || message.includes('network')) return 'NETWORK_ERROR';
    if (message.includes('API') || message.includes('401') || message.includes('403')) return 'API_ERROR';
    if (message.includes('tool') || message.includes('function')) return 'TOOL_ERROR';

    return 'SYSTEM_ERROR';
  }
}

/**
 * Extract structured summary from agent output
 * Looks for markdown sections like "**Execution Summary:**" and extracts from that point
 * Falls back to last 1200 chars if no structured format found
 */
export function extractStructuredSummary(output: string): string | null {
  if (!output || output.length === 0) {
    return null;
  }

  // Look for markdown headings indicating structured format
  const summaryMarkers = [
    /\*\*Execution Summary:\*\*/i,
    /### Work Completed/i,
    /## Execution Summary/i,
    /# Summary/i
  ];

  for (const marker of summaryMarkers) {
    if (marker.test(output)) {
      // Extract from marker to end (or to next major section)
      const match = output.match(marker);
      if (match && match.index !== undefined) {
        // Extract until end or next major heading (that's not part of the summary)
        const remaining = output.slice(match.index);

        // Don't cut off if we find internal headings like "### Actions Taken"
        // Only cut off if we find something that looks like a new top-level section
        // For now, just take everything from the marker to the end
        return remaining.trim();
      }
    }
  }

  // Fallback: Last 1200 chars (current behavior)
  return output.slice(-1200);
}

/**
 * Extract job instance status update from agent output
 * Looks for explicit marker and captures until section boundary
 * Status updates should be single sentences, but we handle line wrapping gracefully
 */
export function extractJobInstanceStatusUpdate(output: string): string | null {
  if (!output || output.length === 0) {
    return null;
  }

  // Strip ANSI codes to ensure reliable pattern matching
  const cleanOutput = stripAnsi(output);

  // Collect all matches with their positions
  const candidates: Array<{ text: string; index: number }> = [];

  // 1. Look for fenced status blocks (```status ... ```) - primary pattern
  // This handles multi-line status updates reliably
  const fencedBlockMatches = cleanOutput.matchAll(/```status\s*\n([\s\S]*?)```/gi);
  for (const match of fencedBlockMatches) {
    if (match[1] && match.index !== undefined) {
      candidates.push({ text: match[1], index: match.index });
    }
  }

  // 2. Look for legacy explicit text markers (Status Update: ...)
  // Capture content until: blank line, Execution Summary, another Status Update, or section header
  // The pattern captures across line breaks until a clear boundary
  const textMatches = cleanOutput.matchAll(
    /(?:\*\*|#+\s*)?Status Update:?(?:\*\*)?\s*([\s\S]+?)(?=\n\s*\n|\nExecution Summary|\n(?:\*\*|#+\s*)?Status Update|\n---|\n#{1,3}\s|$)/gi
  );
  for (const match of textMatches) {
    if (match[1] && match.index !== undefined) {
      candidates.push({ text: match[1], index: match.index });
    }
  }

  // 3. Look for TaskStatus from task_boundary tool calls
  // Supports strictly quoted JSON ("TaskStatus": "...") and looser CLI args (TaskStatus="...")
  const taskStatusMatches = cleanOutput.matchAll(/["']?TaskStatus["']?\s*[:=]\s*["']([^"']+)["']/g);
  for (const match of taskStatusMatches) {
    if (match[1] && match.index !== undefined) {
      candidates.push({ text: match[1], index: match.index });
    }
  }

  // 4. Look for explicit JSON property (jobInstanceStatusUpdate)
  const jsonMatches = cleanOutput.matchAll(/"jobInstanceStatusUpdate"\s*:\s*"([^"]+)"/g);
  for (const match of jsonMatches) {
    if (match[1] && match.index !== undefined) {
      candidates.push({ text: match[1], index: match.index });
    }
  }

  // Return the last match (furthest in the output)
  if (candidates.length === 0) {
    return null;
  }

  const lastMatch = candidates.reduce((a, b) => (a.index > b.index ? a : b));

  // Clean up: collapse multiple whitespace/newlines into single space
  const cleaned = lastMatch.text.replace(/\s+/g, ' ').trim();
  return cleaned || null;
}
