/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "DeliveryActivityChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.DeliveryActivityChecker__factory>;
    getContractFactory(
      name: "IMechMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMechMarketplace__factory>;
    getContractFactory(
      name: "IMultisig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMultisig__factory>;
    getContractFactory(
      name: "IWhitelistManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IWhitelistManager__factory>;
    getContractFactory(
      name: "IMechMarketplace",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMechMarketplace__factory>;
    getContractFactory(
      name: "IMultisig",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IMultisig__factory>;
    getContractFactory(
      name: "WhitelistedRequesterActivityChecker",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.WhitelistedRequesterActivityChecker__factory>;

    getContractAt(
      name: "DeliveryActivityChecker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.DeliveryActivityChecker>;
    getContractAt(
      name: "IMechMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMechMarketplace>;
    getContractAt(
      name: "IMultisig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMultisig>;
    getContractAt(
      name: "IWhitelistManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IWhitelistManager>;
    getContractAt(
      name: "IMechMarketplace",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMechMarketplace>;
    getContractAt(
      name: "IMultisig",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IMultisig>;
    getContractAt(
      name: "WhitelistedRequesterActivityChecker",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.WhitelistedRequesterActivityChecker>;

    deployContract(
      name: "DeliveryActivityChecker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DeliveryActivityChecker>;
    deployContract(
      name: "IMechMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMechMarketplace>;
    deployContract(
      name: "IMultisig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMultisig>;
    deployContract(
      name: "IWhitelistManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWhitelistManager>;
    deployContract(
      name: "IMechMarketplace",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMechMarketplace>;
    deployContract(
      name: "IMultisig",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMultisig>;
    deployContract(
      name: "WhitelistedRequesterActivityChecker",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WhitelistedRequesterActivityChecker>;

    deployContract(
      name: "DeliveryActivityChecker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.DeliveryActivityChecker>;
    deployContract(
      name: "IMechMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMechMarketplace>;
    deployContract(
      name: "IMultisig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMultisig>;
    deployContract(
      name: "IWhitelistManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IWhitelistManager>;
    deployContract(
      name: "IMechMarketplace",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMechMarketplace>;
    deployContract(
      name: "IMultisig",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IMultisig>;
    deployContract(
      name: "WhitelistedRequesterActivityChecker",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.WhitelistedRequesterActivityChecker>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
