/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DeliveryActivityCheckerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getMultisigNonces"
      | "isRatioPass"
      | "livenessRatio"
      | "mechMarketplace"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getMultisigNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRatioPass",
    values: [BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "livenessRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mechMarketplace",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getMultisigNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRatioPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "livenessRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mechMarketplace",
    data: BytesLike
  ): Result;
}

export interface DeliveryActivityChecker extends BaseContract {
  connect(runner?: ContractRunner | null): DeliveryActivityChecker;
  waitForDeployment(): Promise<this>;

  interface: DeliveryActivityCheckerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getMultisigNonces: TypedContractMethod<
    [multisig: AddressLike],
    [bigint[]],
    "view"
  >;

  isRatioPass: TypedContractMethod<
    [curNonces: BigNumberish[], lastNonces: BigNumberish[], ts: BigNumberish],
    [boolean],
    "view"
  >;

  livenessRatio: TypedContractMethod<[], [bigint], "view">;

  mechMarketplace: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getMultisigNonces"
  ): TypedContractMethod<[multisig: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "isRatioPass"
  ): TypedContractMethod<
    [curNonces: BigNumberish[], lastNonces: BigNumberish[], ts: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "livenessRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mechMarketplace"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
