/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMechMarketplace,
  IMechMarketplaceInterface,
} from "../../DeliveryActivityChecker.sol/IMechMarketplace";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "mech",
        type: "address",
      },
    ],
    name: "mapDeliveryCounts",
    outputs: [
      {
        internalType: "uint256",
        name: "deliveryCount",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMechMarketplace__factory {
  static readonly abi = _abi;
  static createInterface(): IMechMarketplaceInterface {
    return new Interface(_abi) as IMechMarketplaceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMechMarketplace {
    return new Contract(address, _abi, runner) as unknown as IMechMarketplace;
  }
}
