/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMultisig,
  IMultisigInterface,
} from "../../WhitelistedRequesterActivityChecker.sol/IMultisig";

const _abi = [
  {
    inputs: [],
    name: "nonce",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IMultisig__factory {
  static readonly abi = _abi;
  static createInterface(): IMultisigInterface {
    return new Interface(_abi) as IMultisigInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IMultisig {
    return new Contract(address, _abi, runner) as unknown as IMultisig;
  }
}
