/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface WhitelistedRequesterActivityCheckerInterface
  extends Interface {
  getFunction(
    nameOrSignature:
      | "addToWhitelist"
      | "canStake"
      | "dynamicWhitelist"
      | "getMultisigNonces"
      | "initialWhitelist1"
      | "initialWhitelist2"
      | "isRatioPass"
      | "isRatioPassWithWhitelist"
      | "isWhitelisted"
      | "livenessRatio"
      | "mechMarketplace"
      | "owner"
      | "removeFromWhitelist"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressRemovedFromWhitelist"
      | "AddressWhitelisted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dynamicWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMultisigNonces",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialWhitelist1",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialWhitelist2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isRatioPass",
    values: [BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRatioPassWithWhitelist",
    values: [AddressLike, BigNumberish[], BigNumberish[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "livenessRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "mechMarketplace",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "canStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dynamicWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMultisigNonces",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialWhitelist1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initialWhitelist2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRatioPass",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRatioPassWithWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "livenessRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mechMarketplace",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AddressRemovedFromWhitelistEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AddressWhitelistedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface WhitelistedRequesterActivityChecker extends BaseContract {
  connect(runner?: ContractRunner | null): WhitelistedRequesterActivityChecker;
  waitForDeployment(): Promise<this>;

  interface: WhitelistedRequesterActivityCheckerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  canStake: TypedContractMethod<[multisig: AddressLike], [boolean], "view">;

  dynamicWhitelist: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getMultisigNonces: TypedContractMethod<
    [multisig: AddressLike],
    [bigint[]],
    "view"
  >;

  initialWhitelist1: TypedContractMethod<[], [string], "view">;

  initialWhitelist2: TypedContractMethod<[], [string], "view">;

  isRatioPass: TypedContractMethod<
    [curNonces: BigNumberish[], lastNonces: BigNumberish[], ts: BigNumberish],
    [boolean],
    "view"
  >;

  isRatioPassWithWhitelist: TypedContractMethod<
    [
      multisig: AddressLike,
      curNonces: BigNumberish[],
      lastNonces: BigNumberish[],
      ts: BigNumberish
    ],
    [boolean],
    "view"
  >;

  isWhitelisted: TypedContractMethod<[account: AddressLike], [boolean], "view">;

  livenessRatio: TypedContractMethod<[], [bigint], "view">;

  mechMarketplace: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeFromWhitelist: TypedContractMethod<
    [account: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canStake"
  ): TypedContractMethod<[multisig: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dynamicWhitelist"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getMultisigNonces"
  ): TypedContractMethod<[multisig: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initialWhitelist1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "initialWhitelist2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isRatioPass"
  ): TypedContractMethod<
    [curNonces: BigNumberish[], lastNonces: BigNumberish[], ts: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRatioPassWithWhitelist"
  ): TypedContractMethod<
    [
      multisig: AddressLike,
      curNonces: BigNumberish[],
      lastNonces: BigNumberish[],
      ts: BigNumberish
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<[account: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "livenessRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "mechMarketplace"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<[account: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AddressRemovedFromWhitelist"
  ): TypedContractEvent<
    AddressRemovedFromWhitelistEvent.InputTuple,
    AddressRemovedFromWhitelistEvent.OutputTuple,
    AddressRemovedFromWhitelistEvent.OutputObject
  >;
  getEvent(
    key: "AddressWhitelisted"
  ): TypedContractEvent<
    AddressWhitelistedEvent.InputTuple,
    AddressWhitelistedEvent.OutputTuple,
    AddressWhitelistedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AddressRemovedFromWhitelist(address)": TypedContractEvent<
      AddressRemovedFromWhitelistEvent.InputTuple,
      AddressRemovedFromWhitelistEvent.OutputTuple,
      AddressRemovedFromWhitelistEvent.OutputObject
    >;
    AddressRemovedFromWhitelist: TypedContractEvent<
      AddressRemovedFromWhitelistEvent.InputTuple,
      AddressRemovedFromWhitelistEvent.OutputTuple,
      AddressRemovedFromWhitelistEvent.OutputObject
    >;

    "AddressWhitelisted(address)": TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;
    AddressWhitelisted: TypedContractEvent<
      AddressWhitelistedEvent.InputTuple,
      AddressWhitelistedEvent.OutputTuple,
      AddressWhitelistedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
